name: gee_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - earthengine-api
  - gsutil
  - gdal
  - pandas
  - numpy
  - geopandas
  - scikit-learn
  - jupyterlab
  - loguru
  - pyyaml
  - geemap
  - cartopy
  - dvc
  - dvc-gs
  - optuna
  - optuna-dashboard
  - seaborn
