name: geospatial
channels:
  - conda-forge
dependencies:
  - python=3.12
  - earthengine-api
  - gsutil
  - gdal
  - pandas
  - numpy
  - geopandas
  - xarray
  - rioxarray
  - scikit-learn
  - jupyterlab
  - loguru
  - pyyaml
  - hvplot
  - cartopy
