name: oemc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - cartopy
  - geemap
  - geopandas
  - earthengine-api
  - google-api-python-client
  - hvplot
  - loguru
  - matplotlib
  - numpy
  - optuna
  - optuna-dashboard
  - pandas
  - pillow
  - protobuf
  - pyproj
  - pyyaml
  - rasterio
  - rioxarray
  - scikit-learn=1.7.2
  - scipy
  - dvc
  - dvc-gs
  - seaborn
  - tqdm
  - mysqlclient
  - pip
  - pip:
    - git+https://github.com/Open-Earth-Monitor/zen#egg=zen
    - git+https://github.com/google/Xee.git@refs/pull/275/head
    - rio-cogeo
