prosail_params:
  CHL: 
    distribution: 'insitu_foliar_codistribution'
  CAR: 
    distribution: 'insitu_foliar_codistribution'
  ANT: 
    distribution: 'constant'
    value: 0.0
  LMA: 
    distribution: 'insitu_foliar_codistribution'
  EWT: 
    distribution: 'insitu_foliar_codistribution'
  N: 
    distribution: 'truncnorm'
    mean: 1.5
    std: 0.6
    min: 1.2
    max: 2.8      
  BROWN: 
    distribution: 'constant'
    value: 0.0
  lai: 
    distribution: 'uniform'
    min: 0.0
    max: 7.0
  LIDFa: 
    distribution: 'truncnorm'
    mean: 60.0
    std: 30.0
    min: 30.0
    max: 80.0
  q: 
    distribution: 'truncnorm'
    mean: 0.2
    std: 0.5
    min: 0.1
    max: 0.5
  TypeLidf: 
    distribution: 'constant'
    value: 2
  alpha: 
    distribution: 'constant'
    value: 40
  tts: 
    distribution: 's2_angles_gee_samples'
  tto: 
    distribution: 's2_angles_gee_samples'
  psi: 
    distribution: 's2_angles_gee_samples'
  psoil: 
    distribution: 'truncnorm'
    mean: 0.25
    std: 0.6
    min: 0.0
    max: 1.0
