prosail_params:
  CHL: 
    distribution: 'truncnorm'
    mean: 45.0
    std: 20.0
    min: 5.0
    max: 100.0
  CAR: 
    distribution: 'truncnorm'
    mean: 7.0
    std: 3.0
    min: 0.0
    max: 15.0
  ANT: 
    distribution: 'constant'
    value: 0.0
  LMA: 
    distribution: 'truncnorm'
    mean: 0.025
    std: 0.02
    min: 0.001
    max: 0.05
  EWT: 
    distribution: 'constant'
    value: 0.02
  N: 
    distribution: 'truncnorm'
    mean: 1.5
    std: 0.5
    min: 1.0
    max: 3.0
  BROWN: 
    distribution: 'constant'
    value: 0.0
  lai: 
    distribution: 'truncnorm'
    min: 0.0
    max: 9.0
    mean: 4.5
    std: 4
  LIDFa: 
    distribution: 'truncnorm'
    mean: 50.0
    std: 7.0
    min: 30.0
    max: 70.0
  q: 
    distribution: 'ratio'
    base_param: 'lai'
    value: 0.5
  TypeLidf: 
    distribution: 'constant'
    value: 2
  alpha: 
    distribution: 'constant'
    value: 40
  tts: 
    distribution: 's2_angles_gee_samples'
  tto: 
    distribution: 's2_angles_gee_samples
  psi: 
    distribution: 's2_angles_gee_samples
  psoil: 
    distribution: 'truncnorm'
    mean: 0.5
    std: 0.25
    min: 0.0
    max: 1.0
