prosail_params:
  CHL: 
    distribution: 'truncnorm'
    mean: 50.0
    std: 20.0
    min: 5.0
    max: 100.0
  CAR: 
    distribution: 'truncnorm'
    mean: 7.5
    std: 3.5
    min: 0.0
    max: 15.0
  ANT: 
    distribution: 'constant'
    value: 0.0
  LMA: 
    distribution: 'truncnorm'
    mean: 0.015
    std: 0.005
    min: 0.001
    max: 0.03
  Cw_rel:
    distribution: 'uniform'
    min: 0.55
    max: 0.95
  N: 
    distribution: 'truncnorm'
    mean: 1.75
    std: 0.5
    min: 1.0
    max: 2.5
  BROWN: 
    distribution: 'uniform'
    min: 0.0
    max: 0.2
  lai: 
    distribution: 'OPTUNA_truncnorm'
  #   min: 0.0
  #   max: 7.0
  LIDFa: 
    distribution: 'truncnorm'
    mean: 55.0
    std: 10.0
    min: 30.0
    max: 80.0
  q: 
    distribution: 'constant'
    value: 0.01
  TypeLidf: 
    distribution: 'constant'
    value: 2
  alpha: 
    distribution: 'constant'
    value: 40
  tts: 
    distribution: 'uniform'
    min: 15.0
    max: 80.0
  tto: 
    distribution: 'uniform'
    min: 0.0
    max: 12
  psi: 
    distribution: 'uniform'
    min: 0.0
    max: 180.0
  psoil: 
    distribution: 'uniform'
    min: 0.0
    max: 1.0
