project:
  type: default
  output-dir: _output

execute:
  echo: false
  warning: false
  message: false
  freeze: false

format:
  pdf:
    documentclass: article
    toc: false
    number-sections: false
    fig-pos: H
    tbl-cap-location: top
