PIPELINE_PARAMS:
  SINGLE_ECOREGION: Null
  # CONTINENT: 'EU'
  YEAR: '2022'
  OUTPUT_RESOLUTION: 10 # in meters
  CAST_TO_INT16: TRUE
  # TRAIT_LIST: ['lai', 'fapar', 'fcover']
  # TRAIT: 'lai'
  # TRAITS: ['lai', 'fapar', 'fcover']
  TRAITS: ['lai', 'fapar', 'fcover']
  ENSEMBLE_SIZE: 1 
  VERSION: 'v3'
  EXPORT_EPSG: 'EPSG:4326'

INT16_SCALING: 
  lai_mean: 1000
  lai_stdDev: 1000
  CHL_mean: 100
  CHL_stdDev: 100
  EWT_mean: 100000
  EWT_stdDev: 100000
  LMA_mean: 100000
  LMA_stdDev: 100000
  fapar_mean: 10000
  fapar_stdDev: 10000
  fcover_mean: 10000
  fcover_stdDev: 10000

# EPSG_CODES:
#   AF: "EPSG:27701"
#   AN: "EPSG:27702"
#   AS: "EPSG:27703"
#   EU: "EPSG:27704"
#   NA: "EPSG:27705"
#   OC: "EPSG:27706"
#   SA: "EPSG:27707"

# WKT_STRINGS:
#   AF: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",5621452.01998],PARAMETER["false_northing",5990638.42298],PARAMETER["central_meridian",21.5],PARAMETER["latitude_of_origin",8.5],UNIT["Meter",1.0]]'
#   AN: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",3714266.97719],PARAMETER["false_northing",3402016.50625],PARAMETER["central_meridian",0.0],PARAMETER["latitude_of_origin",-90.0],UNIT["Meter",1.0]]' 
#   AS: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",4340913.84808],PARAMETER["false_northing",4812712.92347],PARAMETER["central_meridian",94.0],PARAMETER["latitude_of_origin",47.0],UNIT["Meter",1.0]]'
#   EU: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",5837287.81977],PARAMETER["false_northing",2121415.69617],PARAMETER["central_meridian",24.0],PARAMETER["latitude_of_origin",53.0],UNIT["Meter",1.0]]'
#   NA: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",8264722.17686],PARAMETER["false_northing",4867518.35323],PARAMETER["central_meridian",-97.5],PARAMETER["latitude_of_origin",52.0],UNIT["Meter",1.0]]'
#   OC: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",6988408.5356],PARAMETER["false_northing",7654884.53733],PARAMETER["central_meridian",131.5],PARAMETER["latitude_of_origin",-19.5],UNIT["Meter",1.0]]'
#   SA: 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["false_easting",7257179.23559],PARAMETER["false_northing",5592024.44605],PARAMETER["central_meridian",-60.5],PARAMETER["latitude_of_origin",-14.0],UNIT["Meter",1.0]]'


UNITS: # TODO: need to be verified : currently from here: https://www.mdpi.com/2072-4292/10/1/85
  lai_mean: '[m2/m2]'
  lai_stdDev: '[m2/m2]'
  chl_mean: '[µg/cm2]'
  chl_stdDev: '[µg/cm2]'
  ewt_mean: '[cm]'
  ewt_stdDev: '[cm]'
  lma_mean: '[g/cm2]'
  lma_stdDev: '[g/cm2]'
  fapar_mean: '[]'
  fapar_stdDev: '[]'
  fcover_mean: '[]'
  fcover_stdDev: '[]'

CONDA_PATH: "/Users/remotelogin3/miniconda3/envs/gee_pipeline"

CLOUD_FILTERING:
  CLOUDY_PIXEL_PERCENTAGE: 70 # max initial cloudy pixel percentage
  CLOUD_SCORE_PLUS_THRESHOLD: 0.65
  CLOUD_SCORE_PLUS_BAND: 'cs' # 'cs' or 'cs_cdf' : see https://medium.com/google-earth/all-clear-with-cloud-score-bd6ee2e2235e


GEE_FOLDERS:
  ASSET_FOLDER: 'projects/ee-speckerfelix/assets/open-earth'
  TEMP_FOLDER: 'projects/ee-speckerfelix/assets/temp'
  MODEL_RF_LUT: projects/ee-speckerfelix/assets/open-earth/random_forest_models_and_data
  # MISC_FOLDER: 'projects/crowtherlab/felix/open-earth/misc'
  # CLOUDFREE_FOLDER: 'projects/crowtherlab/felix/open-earth/s2_cloudfree'
  # PREDICTIONS_COLLECTION: 'projects/ee-speckerfelix/assets/open-earth/'
  # S2_ANGLE_COLLECTION: 'projects/ee-speckerfelix/assets/open-earth/s2_angles'
  # VALIDATION_TEST: 'projects/ee-speckerfelix/assets/open-earth/s2_validation_test'
  # PREDICTIONS_TEST: 'projects/ee-speckerfelix/assets/test'

GCLOUD_FOLDERS:
  TEMP_FOLDER: 'gs://felixspecker/open-earth/temp/'

  # BUCKET: 'felixspecker'
  # LOCAL_RAW_FOLDER: '../data_shared/gee_exports/data_raw'
  # LOCAL_MERGED_FOLDER: '../data_shared/gee_exports/data_merged'

