PIPELINE_PARAMS:
  SINGLE_ECOREGION: Null
  # CONTINENT: 'EU'
  YEAR: '2023'
  OUTPUT_RESOLUTION: 100 # in meters
  CAST_TO_INT16: TRUE
  # TRAITS: ['lai'] # only use a single trait for now
  TRAITS: ['fcover']
  # TRAITS: ['fcover']
  ENSEMBLE_SIZE: 5 
  VERSION: 'v10' # refers to version v1.0 of the pipeline

EXPORT_PARAMS: # used for exporting the final trait maps outside of GEE
  YEAR: '2019'
  TRAIT: 'lai'
  BAND: 'mean'
  RESOLUTION: 100
  VERSION: 'v10'
  EPSG: 'EPSG:4326'
  NO_DATA_VALUE: -9999


S2_FILTERING:
  MAX_IMAGES_PER_GROUP: 8 # max number of images to be used for images from the same orbit and tile
  VI_INDEX: 'NDVI' # 'EVI' or 'NDVI', bad results with EVI due to high values in some snow covered areas
  MAX_VI_DIFFERENCE: 0.20 # max difference in EVI for images, taking all images with MAX_EVI_DIFFERENCE to the 90 percentile of EVI values
  VI_MAX_PERCENTILE: 0.95 # max percentile of EVI values to be used for filtering images

INT16_SCALING: 
  lai_mean: 1000
  lai_stdDev: 1000
  CHL_mean: 100
  CHL_stdDev: 100
  EWT_mean: 100000
  EWT_stdDev: 100000
  LMA_mean: 100000
  LMA_stdDev: 100000
  fapar_mean: 10000
  fapar_stdDev: 10000
  fcover_mean: 10000
  fcover_stdDev: 10000

UNITS: # TODO: need to be verified : currently from here: https://www.mdpi.com/2072-4292/10/1/85
  lai_mean: '[m2/m2]'
  lai_stdDev: '[m2/m2]'
  chl_mean: '[µg/cm2]'
  chl_stdDev: '[µg/cm2]'
  ewt_mean: '[cm]'
  ewt_stdDev: '[cm]'
  lma_mean: '[g/cm2]'
  lma_stdDev: '[g/cm2]'
  fapar_mean: '[]'
  fapar_stdDev: '[]'
  fcover_mean: '[]'
  fcover_stdDev: '[]'

CONDA_PATH: "/Users/felix/miniconda3/envs/gee_pipeline"

CLOUD_FILTERING:
  CLOUDY_PIXEL_PERCENTAGE: 70 # max initial cloudy pixel percentage
  CLOUD_SCORE_PLUS_THRESHOLD: 0.65
  CLOUD_SCORE_PLUS_BAND: 'cs' # 'cs' or 'cs_cdf' : see https://medium.com/google-earth/all-clear-with-cloud-score-bd6ee2e2235e

GEE_FOLDERS:
  ASSET_FOLDER: 'projects/ee-speckerfelix/assets/open-earth'
  TEMP_FOLDER: 'projects/ee-speckerfelix/assets/temp'
  MODEL_RF_LUT: projects/ee-speckerfelix/assets/open-earth/random_forest_models_and_data

GCLOUD_FOLDERS:
  TEMP_FOLDER: 'gs://felixspecker/open-earth/temp/'
  BUCKET: 'felixspecker'
  EXPORT_FOLDER_INTERMEDIATE: 'open-earth/trait_maps/intermediate'
  EXPORT_FOLDER_FINAL: 'open-earth/trait_maps/merged'
  EXPORT_FOLDER_FINAL_PUBLIC: 'gs://felixspecker-public/open-earth/trait_maps'

LOCAL_FOLDERS:
  EXPORT_FOLDER_INTERMEDIATE: 'data-local/trait_maps/intermediate'
  EXPORT_FOLDER_FINAL: 'data-local/trait_maps/merged'

  # BUCKET: 'felixspecker'
  # LOCAL_RAW_FOLDER: '../data_shared/gee_exports/data_raw'
  # LOCAL_MERGED_FOLDER: '../data_shared/gee_exports/data_merged'

