# GENERAL PARMAETERS
traits: ['lai', 'CHL', 'LMA', 'EWT']  
reflectance_bands: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
angle_bands: ['tts', 'tto', 'psi']
list_ecoids_in_lai_validation: [399, 717, 392, 430, 686, 543, 344, 353, 429, 396, 366, 331, 338, 795, 428, 393, 648, 402, 664, 647, 193, 339, 654, 435, 407]
list_ecoids_in_foliar_validation: null

# HYPERPARAMETERS FOR LUT CREATION
number_of_samples: 2000
lut_per_ecoregion: True

# prosail params
add_noise: True # from lut_forward_params
modify_rsoil: True  # from lut_forward_params

# posthoc params
# add_s2_baresoil_spectra: True
# add_s2_water_spectra: True
# add_s2_urban_spectra: True
# add_s2_snow_spectra: True
add_s2_nonvegetated_spectra: True


lut_forward_params:
  add_noise:
    noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
    arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      AdditiveNoise: 0.01
      MultiplicativeNoise: 0.04

  
  modify_rsoil:
    rsoil_from_insitu: 
      bool: True
      fraction: 0.5
    rsoil_from_emit:
      bool: False
      fraction: 0.0


add_s2_nonvegetated_spectra:
  add_s2_baresoil_spectra: 
    num_spectra: 100
  add_s2_water_spectra: 
    num_spectra: 20
  add_s2_urban_spectra:
    num_spectra: 50
  add_s2_snow_spectra:
    num_spectra: 20
    

prosail_params:
  CHL: 
    distribution: 'insitu_foliar_codistribution'
  CAR: 
    distribution: 'insitu_foliar_codistribution'
  ANT: 
    distribution: 'constant'
    value: 0.0
  LMA: 
    distribution: 'insitu_foliar_codistribution'
  EWT: 
    distribution: 'insitu_foliar_codistribution'
  N: 
    distribution: 'truncnorm'
    mean: 1.5
    std: 0.3
    min: 1.2
    max: 1.8      
  BROWN: 
    distribution: 'truncnorm'
    mean: 0.0
    std: 0.3
    min: 0.0
    max: 2.0
  lai: 
    distribution: 'truncnorm'
    mean: 2.0
    std: 3.0
    min: 0.0
    max: 15.0
  LIDFa: 
    distribution: 'truncnorm'
    mean: 60.0
    std: 30.0
    min: 30.0
    max: 80.0
  q: 
    distribution: 'truncnorm'
    mean: 0.2
    std: 0.5
    min: 0.1
    max: 0.5
  TypeLidf: 
    distribution: 'constant'
    value: 2
  alpha: 
    distribution: 'constant'
    value: 40
  tts: 
    distribution: 's2_angles_gee_samples'
  tto: 
    distribution: 's2_angles_gee_samples'
  psi: 
    distribution: 's2_angles_gee_samples'
  psoil: 
    distribution: 'truncnorm'
    mean: 0.25
    std: 0.6
    min: 0.0
    max: 1.0
