# GENERAL PARMAETERS
general_params:
  traits: ['lai', 'CHL', 'LMA', 'EWT']  
  reflectance_bands: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B11', 'B12']
  angle_bands: ['tts', 'tto', 'psi']
  # list_ecoids_in_lai_validation: [399, 717, 392, 430, 686, 543, 344, 353, 429, 396, 366, 331, 338, 795, 428, 393, 648, 402, 664, 647, 193, 339, 654, 435, 407]
  # list_ecoids_in_lai_validation: [399]
  list_ecoids_in_lai_validation: [399, 543, 686, 331] # test_ecos
  list_ecoedids_in_foliar_validation: null

# HYPERPARAMETERS FOR LUT CREATION
hyper_params: 
  # number_of_samples: [1000, 2000, 5000, 10000, 20000]
  number_of_samples: 2000
  # lut_per_ecoregion: [True, False]
  lut_per_ecoregion: True

  # prosail params
  # add_noise: [True, False] # from lut_forward_params
  add_noise: True
  # modify_rsoil: [True, False]  # from lut_forward_params
  # modify_rsoil: True
  modify_rsoil: True

  # posthoc params
  # add_s2_nonvegetated_spectra: [True, False]
  add_s2_nonvegetated_spectra: True

  lut_forward_params:
    add_noise:
      - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
        arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
          AdditiveNoise: 0.01
          MultiplicativeNoise: 0.04
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.01
      #     MultiplicativeNoise: 0.08
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.01
      #     MultiplicativeNoise: 0.02                    
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.005
      #     MultiplicativeNoise: 0.04          
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.02
      #     MultiplicativeNoise: 0.04     
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.005
      #     MultiplicativeNoise: 0.02
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.005
      #     MultiplicativeNoise: 0.08          
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.02
      #     MultiplicativeNoise: 0.08
      # - noise_type: 'add_multi' # should be one of ['atbd', 'add_multi']
      #   arguments:  # should be null for atbd, and have AdditiveNoise and MultiplicativeNoise for add_multi
      #     AdditiveNoise: 0.02
      #     MultiplicativeNoise: 0.02        
      # - noise_type: 'atbd'
      #   arguments: null
    
    modify_rsoil:
      - rsoil_from_insitu: 
          bool: True
          fraction: 0.5
        rsoil_from_emit:
          bool: False
          fraction: 0.0
      # - rsoil_from_insitu: 
      #     bool: False
      #     fraction: 0.0
      #   rsoil_from_emit:
      #     bool: False
      #     fraction: 0.5

  add_s2_baresoil_spectra: 
    - num_spectra: 100
    # - num_spectra: 20
  add_s2_water_spectra: 
    # - num_spectra: 50
    - num_spectra: 20
  add_s2_urban_spectra:
    # - num_spectra: 100
    - num_spectra: 20
  add_s2_snow_spectra:
    - num_spectra: 20
      

  prosail_params:
    CHL: 
      - distribution: 'insitu_foliar_codistribution'
      - distribution: 'truncnorm'
        mean: 45.0
        std: 30.0
        min: 20.0
        max: 90.0
      # - distribution: 'uniform'
      #   min: 0.0
      #   max: 100.0
      # - distribution: 'truncnorm'
      #   mean: 35.0
      #   std: 30.0
      #   min: 5.0
      #   max: 75.0
    CAR: 
      - distribution: 'insitu_foliar_codistribution'
      - distribution: 'ratio'
        ratio: 0.14
        base_param: 'CHL'
      # - distribution: 'truncnorm'
      #   mean: 10
      #   std: 10
      #   min: 0.0
      #   max: 20.0
    ANT: 
      distribution: 'constant'
      value: 0.0
    LMA: 
      - distribution: 'insitu_foliar_codistribution'
      - distribution: 'truncnorm'
        mean: 0.005
        std: 0.003
        min: 0.003
        max: 0.011
      # - distribution: 'truncnorm'
      #   mean: 0.005
      #   std: 0.005
      #   min: 0.002
      #   max: 0.02
      # - distribution: 'truncnorm'
      #   mean: 0.005
      #   std: 0.001
      #   min: 0.001
      #   max: 0.03
    EWT: 
      - distribution: 'insitu_foliar_codistribution'
      - distribution: 'truncnorm'
        mean: 0.018
        std: 0.006
        min: 0.005
        max: 0.04
      # - distribution: 'truncnorm'
      #   mean: 0.012
      #   std: 0.006
      #   min: 0.005
      #   max: 0.035
      # - distribution: 'truncnorm'
      #   mean: 0.02
      #   std: 0.01
      #   min: 0.002
      #   max: 0.05
    N: 
      - distribution: 'truncnorm'
        mean: 1.5
        std: 0.3
        min: 1.2
        max: 1.8      
      # - distribution: 'truncnorm'
      #   mean: 1.5
      #   std: 0.5
      #   min: 1.0
      #   max: 2.7
      # - distribution: 'uniform'
      #   min: 1.3
      #   max: 2.5
    BROWN: 
      - distribution: 'truncnorm'
        mean: 0.0
        std: 0.3
        min: 0.0
        max: 2.0
      # - distribution: 'constant'
      #   value: 0.0
    lai: 
      - distribution: 'truncnorm'
        mean: 2.0
        std: 3.0
        min: 0.0
        max: 15.0
      # - distribution: 'uniform'
      #   min: 0.0
      #   max: 7.0
      # - distribution: 'truncnorm'
      #   mean: 2.5
      #   std: 2.0
      #   min: 0.0
      #   max: 9.0
      - distribution: 'truncnorm'
        mean: 3.0
        std: 2.0
        min: 0.0
        max: 7.0
    LIDFa: 
      distribution: 'truncnorm'
      mean: 60.0
      std: 30.0
      min: 30.0
      max: 80.0
    q: 
      distribution: 'truncnorm'
      mean: 0.2
      std: 0.5
      min: 0.1
      max: 0.5
      # - distribution: 'constant'
      #   value: 0.01
    TypeLidf: 
      distribution: 'constant'
      value: 2
    alpha: 
      distribution: 'constant'
      value: 40
    tts: 
      distribution: 's2_angles_gee_samples'
    tto: 
      distribution: 's2_angles_gee_samples'
    psi: 
      distribution: 's2_angles_gee_samples'
    psoil: 
      distribution: 'truncnorm'
      mean: 0.25
      std: 0.6
      min: 0.0
      max: 1.0
